package:
  name: "note-utils"
  version: "0.0.2"

source:
  git_rev: "v0.0.2"
  git_url: "https://github.com/scarface2013/note-utils.git"

requirements:
  host:
    - python
    - setuptools

  run:
    - python

about:
  home: "https://github.com/scarface2013/note-utils"
  license: "MIT"
  license_file: "LICENSE"